support care team invites for care partner app
tidepool-org/hydrophone pull request #126
Opened 2023-09-06 22:58 UTC by ewollesen

https://tidepool.atlassian.net/browse/BACK-2500

2023-10-24 08:10 UTC, toddkazakov requested changes
I found some small inconsistencies that may need to be addressed

2023-10-24 08:10 UTC, toddkazakov commented on api/invite.go
> +	if a.checkForDuplicateInvite(req.Context(), ib.Email, invitorID) {
Won't this logic prevent sending a new follow invite for if one was previously sent but not yet accepted? Do we want to address this?

2023-10-24 08:10 UTC, toddkazakov commented on api/invite.go
> +	fullName := "Mickey Mouse"
🙀🙀🙀

2023-10-24 08:10 UTC, toddkazakov commented on api/invite.go
> +		statusErr := &status.StatusError{Status: status.NewStatus(http.StatusConflict, statusInternalServerErrorMessage)}
Should this be 500 instead of 409?

2023-10-24 08:10 UTC, toddkazakov commented on hydrophone.go
> +func alertsProvider(config OutboundConfig, httpClient *http.Client, shorelineClient shoreline.Client) api.AlertsClient {
Can we generate this client from the spec?

2023-10-24 22:34 UTC, ewollesen commented on api/invite.go
> +			log.Printf("adding permission: %q %+v", key, perms[key])
> Without logging the user id this log message doesn’t add any value, only noise. Same goes for all of the other Printf statements that were added in this PR.

I found the log statements useful for my personal debugging, but I understand that once in production, the addition of a user id will be helpful. Would you prefer I add the user id to the existing messages or just remove them entirely? Please let me know, and I'll make the necessary changes.

> This project already uses zap for logging in some places, but not all of the codebase was updated. I think new code that we add should either use zap (so we can provide structured context like the user id, clinic id, etc.) or replace zap with slog.

I'm curious about the new slog package of course, but the fastest route for me, and the one with the least overall change, is to continue with zap. I'll go that route unless you feel strongly like you want to remove zap in favor of slog. I wouldn't be against that. Given a fresh project, I'd definitely give it a go with slog, but as you noted, zap is already here.

2023-10-24 22:35 UTC, ewollesen commented on api/invite.go
> +				&status.StatusError{Status: status.NewStatus(http.StatusForbidden, statusForbiddenMessage)},
> 403 is usually used when the user is authenticated but they don't have the required permissions for a given action. I don't think that status code is suitable for validation errors. Consider returning 400 or 422.

Good catch, you're right, 400 makes way more sense. Will update.

2023-10-24 22:38 UTC, ewollesen commented on api/invite.go
> +	fullName := "Mickey Mouse"
Doh, thank you!

Obviously didn't mean to leave that in.

2023-10-24 22:39 UTC, ewollesen commented on api/invite.go
> +		statusErr := &status.StatusError{Status: status.NewStatus(http.StatusConflict, statusInternalServerErrorMessage)}
> Should this be 500 instead of 409?

Yes, thank you, and fixed.

2023-10-24 22:41 UTC, ewollesen commented on hydrophone.go
> +func alertsProvider(config OutboundConfig, httpClient *http.Client, shorelineClient shoreline.Client) api.AlertsClient {
> Can we generate this client from the spec?

I'm not up to date on what's available at present for that work. Given that I have a client in place that's working for now, how would you feel about me creating a follow-up ticket to address that?

2023-10-24 22:42 UTC, ewollesen commented on api/invite.go
> +	if a.checkForDuplicateInvite(req.Context(), ib.Email, invitorID) {
> Won't this logic prevent sending a new follow invite for if one was previously sent but not yet accepted? Do we want to address this?

I'll investigate and write a test to cover it, if there isn't one that does it already (there probably isn't, but there should be).

2023-10-24 22:44 UTC, ewollesen commented on api/invite.go
> +	if a.checkForDuplicateInvite(req.Context(), ib.Email, invitorID) {
Reading this again, I'm not sure what we want to do... But I'm pretty sure we don't want to worry about it /too/ much, as there are probably at most a small handful of outstanding invites (they have an expiration). In fact, we could do a query to check how many outstanding invites there are at present. I wouldn't be surprised if it was 0, but that's just based on my impressions of what @ps2 has said about the usage of the current invitations, and not any data. Pete might have better data, or even just a better gut-feel than I do.

2023-10-24 22:51 UTC, ewollesen commented on api/invite.go
> +	if a.checkForDuplicateInvite(req.Context(), ib.Email, invitorID) {
I think I remember discussing this with Pete, and we came to the conclusion, that the user, when faced with this issue, would just have to use the web interface to cancel the pending invite, then they could send a new invite via the CPA. Maybe not the best UX, but it'd work.

That said, in brainstorming this a little, I thought we could do something like what we do when they're an existing member, that is, add an additional check that says, OK, there's a pending invite, but does the pending invite _not_ include alerting, and would the new invite add alerting? If so, merge the two invites. That seems like something that would work, but I'd want to noodle on that a bit before committing to implementing it. Thoughts?

2023-10-24 23:02 UTC, ewollesen commented on api/invite.go
> +	if a.checkForDuplicateInvite(req.Context(), ib.Email, invitorID) {
Another option, is that the CPA could dismiss any pending invites before it tries to send the new one, and of course inform the user: "Sending this invitation will revoke any outstanding invitations to the user, this cannot be undone." or such.

2023-10-24 23:15 UTC, ewollesen commented on api/invite.go
> +			log.Printf("adding permission: %q %+v", key, perms[key])
I'm going to start by adding user id and moving my additions to use zap, so if that's not what you'd prefer, please let me know ASAP. :)

2023-10-25 06:53 UTC, toddkazakov commented on api/invite.go
> +			log.Printf("adding permission: %q %+v", key, perms[key])
Using zap and adding the user id sounds good to me. Please make sure you log at the appropriate level - info/debug/trace.

2023-10-25 06:55 UTC, toddkazakov commented on api/invite.go
> +	if a.checkForDuplicateInvite(req.Context(), ib.Email, invitorID) {
Just wanted to make sure this is on your radar - not addressing this right away is ok.

2023-10-25 06:56 UTC, toddkazakov commented on hydrophone.go
> +func alertsProvider(config OutboundConfig, httpClient *http.Client, shorelineClient shoreline.Client) api.AlertsClient {
I don't think we'll ever get to that follow-up ticket given our ever shifting priorities. I'm not a big fan of those manually written clients, but it's ok to leave as is.

2023-10-25 17:30 UTC, ewollesen commented on api/invite.go
> +			log.Printf("adding permission: %q %+v", key, perms[key])
> Please make sure you log at the appropriate level - info/debug/trace.

Every team I've been on has different ideas of what these levels should indicate. Is there any guidance for what Tidepool uses here? Or, if not, at least, what level is production set to?

2023-10-25 17:43 UTC, ps2 commented on api/invite.go
> +	if a.checkForDuplicateInvite(req.Context(), ib.Email, invitorID) {
I think this is managed on the Loop side: we do display pending (unaccepted) invites in Loop, and allow them to resend the invite, which we do by issuing a PATCH to the resource url. So I don't think Loop will be making duplicate requests generally. If they do try to send another invite to the same email, even though they can see the pending invite, then I think displaying an error to the user is fine on the Loop side.

2023-10-25 17:45 UTC, ewollesen commented on api/invite.go
> +			log.Printf("adding permission: %q %+v", key, perms[key])
I didn't add most of the `log.Print*` statements in this file, most of them predate my changes. That said, I'll go ahead and migrate them to zap too. To me, they look mostly like debug statements, so I'm going to go that route in general.

2023-10-31 19:52 UTC, Camji55 commented on api/invite.go
> +	if a.checkForDuplicateInvite(req.Context(), ib.Email, invitorID) {
@ewollesen is there a window in which we allow the user to resend an invite? We have this UI to hit the resend endpoint when the status is pending. Is there some property we can track to determine when to show the resend UI?

![Simulator Screenshot - iPhone 15 Pro - 2023-10-31 at 12 50 46](https://github.com/tidepool-org/hydrophone/assets/2769158/fced089f-cec9-4df9-b89c-2a43bf6d7de2)

2023-10-31 20:20 UTC, ewollesen commented on api/invite.go
> +	if a.checkForDuplicateInvite(req.Context(), ib.Email, invitorID) {
@Camji55 it's messy.

I'll report what I understand from reading the code, which isn't to say this is how it should be, but rather how I think it is at present. :)

One can resend a *pending* invite at any time, so long as said invite exists, and the user still has the necessary permissions to send it in the first place. An accepted, revoked, or declined invite is not pending, of course.

There does exist a concept of invitation expiration, however it's only checked when sending a brand new invite. That is, SendInvite checks if there's an existing pending invite, and if it's "expired", then it will create and send a new invite. But this happens only through the SendInvite method/endpoint, *not* the ResendInvite method/endpoint which seems like it probably isn't the intended behavior. 

I read the tests to see if they could shed some light, but sadly the hydrophone project has poor tests I'm afraid, and I don't detect any tests of the ResendInvite method/endpoint, so there's no help to be gained there. I'd have to dig for a Jira ticket or design doc to see if there are any hints how this was supposed to work. Maybe @darinkrauss, as our team historian, can illuminate us?

2023-10-31 23:22 UTC, ewollesen commented on hydrophone.go
> +func alertsProvider(config OutboundConfig, httpClient *http.Client, shorelineClient shoreline.Client) api.AlertsClient {
After trying to wrangle the code generator into putting out something useful, and failing, I'm going to take a pass on this.

I'll move the hand-rolled client to the platform repo, but we'll have to take another stab at generation another time. That's yet to come.

2023-11-01 14:18 UTC, ewollesen commented on hydrophone.go
> +func alertsProvider(config OutboundConfig, httpClient *http.Client, shorelineClient shoreline.Client) api.AlertsClient {
After struggling to get oapi-codegen to produce the types desirable, we've decided that it's best for now to just move the existing hand-rolled client into platform, and we can continue in future to find a new solution that provides the consistency and accuracy in relation to our OpenAPI spec that we're hoping for.

2023-11-27 12:18 UTC, toddkazakov requested changes
When logging an error with zap, the line entry contains both a message and an error. There are many places in this PR where the log message we were logging previously was deleted. In addition to that, I see some info level messages there were also deleted. I don't think this is the direction we should be going to.

When adding the userid to the context it's important that we log both the id of the user  making the request and the one defined in the url. 

If it's possible can you please create a new PR with all logging related changes that's stacked on top of the care team invites work, because the diff doesn't even render in the browser for me.

2024-01-31 20:30 UTC, closed without merging